### ISSUE TITLE
wifiphisher issue

### ISSUE THREAD

**Issue by minebul** [minebul/Help#1]
<```
root@kali:~# wifiphisher
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 27, in <module>
    import wifiphisher.common.accesspoint as accesspoint
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/accesspoint.py", line 7, in <module>
    from roguehostapd import hostapd_controller
ImportError: cannot import name hostapd_controller
```>

here i have some troubles... Please help me!

**Comment by minebul** [comment]
i have already deleted/installed roguehostapd and it still isnt working
